global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'majestic-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['majestic-api:5050']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']